public with sharing class SearchAccountController {
   
    /*
    Method: searchAccount
    Para: Account Name
    here passing the Account Name to Fetching all the releated Accounts
    */
    @AuraEnabled (cacheable = true)
    public static List<Account> searchAccount(String accName) {
        string strAccName = '%'+ accName + '%';
        return [Select Id, Name, BillingState, Phone from Account WHERE Name LIKE: strAccName ];
    }
}
