public with sharing class RfTestingController {

    public PageReference firstPageNext() {
        system.debug('first page next is executing');
        system.debug('first page next is executing');
        system.debug('first page next is executing');
        system.debug('first page next is executing');
        return null;
    }

    public class testing {
    public void firstPageNext()
    {
        system.debug('first page next is executing');
        system.debug('first page next is executing');
        system.debug('first page next is executing');
        system.debug('first page next is executing');
     }
}
    
}